# Generated by Django 5.0.14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('import_type', models.CharField(choices=[('product', 'Ürün'), ('order', 'Sipariş'), ('stock', 'Stok'), ('customer', 'Müşteri')], max_length=20, verbose_name='İçe Aktarım Tipi')),
                ('file_name', models.CharField(max_length=255, verbose_name='Dosya Adı')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('total_rows', models.IntegerField(default=0, verbose_name='Toplam Satır')),
                ('processed_rows', models.IntegerField(default=0, verbose_name='İşlenen Satır')),
                ('success_count', models.IntegerField(default=0, verbose_name='Başarılı')),
                ('error_count', models.IntegerField(default=0, verbose_name='Hatalı')),
                ('skipped_count', models.IntegerField(default=0, verbose_name='Atlanan')),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='İlerleme %')),
                ('current_chunk', models.IntegerField(default=0, verbose_name='Mevcut Parça')),
                ('total_chunks', models.IntegerField(default=0, verbose_name='Toplam Parça')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Ayarlar')),
                ('result_summary', models.JSONField(blank=True, default=dict, verbose_name='Sonuç Özeti')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Başlama Zamanı')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Zamanı')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata Mesajı')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'İçe Aktarım İşlemi',
                'verbose_name_plural': 'İçe Aktarım İşlemleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Şablon Adı')),
                ('import_type', models.CharField(choices=[('product', 'Ürün'), ('order', 'Sipariş'), ('stock', 'Stok'), ('customer', 'Müşteri')], max_length=20, verbose_name='İçe Aktarım Tipi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('field_mapping', models.JSONField(default=dict, verbose_name='Alan Eşleşmeleri')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Ayarlar')),
                ('sample_data', models.JSONField(blank=True, default=list, verbose_name='Örnek Veri')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'İçe Aktarım Şablonu',
                'verbose_name_plural': 'İçe Aktarım Şablonları',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='İşlem')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Ek Bilgi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.importjob', verbose_name='İçe Aktarım İşlemi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'İçe Aktarım Geçmişi',
                'verbose_name_plural': 'İçe Aktarım Geçmişleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(verbose_name='Satır Numarası')),
                ('column_name', models.CharField(blank=True, max_length=100, verbose_name='Sütun Adı')),
                ('error_type', models.CharField(choices=[('validation', 'Doğrulama Hatası'), ('not_found', 'Bulunamadı'), ('duplicate', 'Mükerrer Kayıt'), ('permission', 'Yetki Hatası'), ('format', 'Format Hatası'), ('system', 'Sistem Hatası'), ('other', 'Diğer')], default='other', max_length=20, verbose_name='Hata Tipi')),
                ('error_message', models.TextField(verbose_name='Hata Mesajı')),
                ('row_data', models.JSONField(blank=True, default=dict, verbose_name='Satır Verisi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='core.importjob', verbose_name='İçe Aktarım İşlemi')),
            ],
            options={
                'verbose_name': 'İçe Aktarım Hatası',
                'verbose_name_plural': 'İçe Aktarım Hataları',
                'ordering': ['import_job', 'row_number'],
            },
        ),
    ]