# Generated by Django 5.0.14 on 2025-05-18 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial_import_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomFieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when this record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        choices=[
                            ("product", "Ürün"),
                            ("order", "Sipariş"),
                            ("customer", "Müşteri"),
                            ("invoice", "Fatura"),
                        ],
                        help_text="Özel alanın ekleneceği model",
                        max_length=50,
                        verbose_name="Model Adı",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Veritabanındaki alan adı (küçük harfler ve alt çizgi kullanın)",
                        max_length=50,
                        verbose_name="Alan Adı",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Kullanıcıya gösterilecek alan adı",
                        max_length=100,
                        verbose_name="Etiket",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        help_text="Alanın veri tipi",
                        max_length=50,
                        verbose_name="Alan Tipi",
                    ),
                ),
                (
                    "help_text",
                    models.CharField(
                        blank=True,
                        help_text="Alan için açıklayıcı metin",
                        max_length=200,
                        verbose_name="Yardım Metni",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=False,
                        help_text="Bu alan zorunlu mu?",
                        verbose_name="Zorunlu",
                    ),
                ),
                (
                    "default_value",
                    models.TextField(
                        blank=True,
                        help_text="Alan için varsayılan değer",
                        verbose_name="Varsayılan Değer",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Alan tipi için ek seçenekler",
                        verbose_name="Seçenekler",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Görüntüleme sırası", verbose_name="Sıra"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Bu alan aktif mi?",
                        verbose_name="Aktif",
                    ),
                ),
                (
                    "show_in_list",
                    models.BooleanField(
                        default=True,
                        help_text="Bu alan liste görünümünde gösterilsin mi?",
                        verbose_name="Listede Göster",
                    ),
                ),
                (
                    "show_in_form",
                    models.BooleanField(
                        default=True,
                        help_text="Bu alan form görünümünde gösterilsin mi?",
                        verbose_name="Formda Göster",
                    ),
                ),
                (
                    "searchable",
                    models.BooleanField(
                        default=False,
                        help_text="Bu alanda arama yapılabilsin mi?",
                        verbose_name="Aranabilir",
                    ),
                ),
            ],
            options={
                "verbose_name": "Özel Alan Tanımı",
                "verbose_name_plural": "Özel Alan Tanımları",
                "ordering": ["model_name", "order", "field_name"],
            },
        ),
        migrations.CreateModel(
            name="DetailedImportResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.IntegerField(verbose_name="Satır Numarası")),
                ("data", models.JSONField(verbose_name="Veri")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Oluşturuldu"),
                            ("updated", "Güncellendi"),
                            ("skipped", "Atlandı"),
                            ("failed", "Başarısız"),
                            ("partial", "Kısmi Başarılı"),
                        ],
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "fields_updated",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Güncellenen Alanlar"
                    ),
                ),
                (
                    "fields_failed",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Başarısız Alanlar"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="Hata Mesajı"),
                ),
                (
                    "error_details",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Hata Detayları"
                    ),
                ),
                (
                    "dependent_operations",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Bağımlı İşlemler"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Detaylı İçe Aktarma Sonucu",
                "verbose_name_plural": "Detaylı İçe Aktarma Sonuçları",
                "ordering": ["import_task", "row_number"],
            },
        ),
        migrations.CreateModel(
            name="ImportSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_rows",
                    models.IntegerField(default=0, verbose_name="Toplam Satır"),
                ),
                (
                    "successful_rows",
                    models.IntegerField(default=0, verbose_name="Başarılı Satır"),
                ),
                (
                    "failed_rows",
                    models.IntegerField(default=0, verbose_name="Başarısız Satır"),
                ),
                (
                    "skipped_rows",
                    models.IntegerField(default=0, verbose_name="Atlanan Satır"),
                ),
                (
                    "partial_rows",
                    models.IntegerField(default=0, verbose_name="Kısmi Başarılı Satır"),
                ),
                (
                    "created_count",
                    models.IntegerField(default=0, verbose_name="Oluşturulan Kayıt"),
                ),
                (
                    "updated_count",
                    models.IntegerField(default=0, verbose_name="Güncellenen Kayıt"),
                ),
                (
                    "field_success_rates",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Alan Başarı Oranları"
                    ),
                ),
                (
                    "error_summary",
                    models.JSONField(blank=True, null=True, verbose_name="Hata Özeti"),
                ),
                (
                    "processing_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="İşlem Süresi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "İçe Aktarma Özeti",
                "verbose_name_plural": "İçe Aktarma Özetleri",
            },
        ),
        migrations.CreateModel(
            name="ImportTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("product", "Ürün"),
                            ("customer", "Müşteri"),
                            ("order", "Sipariş"),
                            ("stock", "Stok"),
                        ],
                        max_length=20,
                        verbose_name="Tür",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Bekliyor"),
                            ("processing", "İşleniyor"),
                            ("completed", "Tamamlandı"),
                            ("failed", "Başarısız"),
                            ("partial", "Kısmi Başarılı"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Dosya Adı"),
                ),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="Dosya Yolu"),
                ),
                (
                    "progress",
                    models.IntegerField(default=0, verbose_name="İlerleme (%)"),
                ),
                (
                    "current_row",
                    models.IntegerField(default=0, verbose_name="İşlenen Satır"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Başlangıç Zamanı"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bitiş Zamanı"
                    ),
                ),
            ],
            options={
                "verbose_name": "İçe Aktarma Görevi",
                "verbose_name_plural": "İçe Aktarma Görevleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RuleSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Kural Seti Adı"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="Model Adı"),
                ),
                (
                    "field_name",
                    models.CharField(max_length=100, verbose_name="Alan Adı"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kural Seti",
                "verbose_name_plural": "Kural Setleri",
                "db_table": "rule_sets",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ValidationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(verbose_name="Değer")),
                ("is_valid", models.BooleanField(verbose_name="Geçerli")),
                ("errors", models.JSONField(default=list, verbose_name="Hatalar")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Doğrulama Logu",
                "verbose_name_plural": "Doğrulama Logları",
                "db_table": "validation_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ValidationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Kural Adı")),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("required", "Zorunlu Alan"),
                            ("regex", "Regex (Düzenli İfade)"),
                            ("range", "Sayı Aralığı"),
                            ("length", "Metin Uzunluğu"),
                            ("choices", "Seçenekler"),
                            ("email", "E-posta"),
                            ("phone", "Telefon"),
                            ("url", "URL"),
                            ("tckn", "TC Kimlik No"),
                            ("date", "Tarih"),
                            ("custom", "Özel"),
                        ],
                        max_length=20,
                        verbose_name="Kural Tipi",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(default=dict, verbose_name="Parametreler"),
                ),
                (
                    "error_message",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Hata Mesajı"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Doğrulama Kuralı",
                "verbose_name_plural": "Doğrulama Kuralları",
                "db_table": "validation_rules",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="importerror",
            name="import_job",
        ),
        migrations.RemoveField(
            model_name="importjob",
            name="user",
        ),
        migrations.RemoveField(
            model_name="importhistory",
            name="import_job",
        ),
        migrations.RemoveField(
            model_name="importtemplate",
            name="created_by",
        ),
        migrations.AlterModelOptions(
            name="importhistory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Import Geçmişi",
                "verbose_name_plural": "Import Geçmişleri",
            },
        ),
        migrations.RemoveField(
            model_name="importhistory",
            name="action",
        ),
        migrations.RemoveField(
            model_name="importhistory",
            name="description",
        ),
        migrations.RemoveField(
            model_name="importhistory",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="importhistory",
            name="user",
        ),
        migrations.AddField(
            model_name="importhistory",
            name="can_reload",
            field=models.BooleanField(
                default=True, verbose_name="Yeniden Yüklenebilir"
            ),
        ),
        migrations.AddField(
            model_name="importhistory",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Tamamlanma Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="importhistory",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Oluşturan",
            ),
        ),
        migrations.AddField(
            model_name="importhistory",
            name="error_count",
            field=models.IntegerField(default=0, verbose_name="Hatalı"),
        ),
        migrations.AddField(
            model_name="importhistory",
            name="error_details",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Hata Detayları"
            ),
        ),
        migrations.AddField(
            model_name="importhistory",
            name="file_hash",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Dosya Hash"
            ),
        ),
        migrations.AddField(
            model_name="importhistory",
            name="file_name",
            field=models.CharField(
                default="unknown_file", max_length=255, verbose_name="Dosya Adı"
            ),
        ),
        migrations.AddField(
            model_name="importhistory",
            name="file_path",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Dosya Yolu"
            ),
        ),
        migrations.AddField(
            model_name="importhistory",
            name="file_size",
            field=models.BigIntegerField(default=0, verbose_name="Dosya Boyutu (byte)"),
        ),
        migrations.AddField(
            model_name="importhistory",
            name="import_params",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Import Parametreleri"
            ),
        ),
        migrations.AddField(
            model_name="importhistory",
            name="module",
            field=models.CharField(
                choices=[
                    ("products", "Ürünler"),
                    ("customers", "Müşteriler"),
                    ("orders", "Siparişler"),
                    ("stock", "Stok Hareketleri"),
                    ("stock_adjustment", "Stok Düzeltme"),
                ],
                default="products",
                max_length=50,
                verbose_name="Modül",
            ),
        ),
        migrations.AddField(
            model_name="importhistory",
            name="parent_import",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reload_history",
                to="core.importhistory",
                verbose_name="Ana Import",
            ),
        ),
        migrations.AddField(
            model_name="importhistory",
            name="processed_count",
            field=models.IntegerField(default=0, verbose_name="İşlenen"),
        ),
        migrations.AddField(
            model_name="importhistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Bekliyor"),
                    ("processing", "İşleniyor"),
                    ("completed", "Tamamlandı"),
                    ("failed", "Başarısız"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
        migrations.AddField(
            model_name="importhistory",
            name="success_count",
            field=models.IntegerField(default=0, verbose_name="Başarılı"),
        ),
        migrations.AddField(
            model_name="importhistory",
            name="success_details",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Başarı Detayları"
            ),
        ),
        migrations.AddField(
            model_name="importhistory",
            name="total_count",
            field=models.IntegerField(default=0, verbose_name="Toplam"),
        ),
        migrations.AddField(
            model_name="importhistory",
            name="uid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="importhistory",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name="importhistory",
            index=models.Index(
                fields=["-created_at"], name="core_import_created_237df2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importhistory",
            index=models.Index(fields=["module"], name="core_import_module_566015_idx"),
        ),
        migrations.AddIndex(
            model_name="importhistory",
            index=models.Index(fields=["status"], name="core_import_status_ca4ad6_idx"),
        ),
        migrations.AddIndex(
            model_name="importhistory",
            index=models.Index(
                fields=["created_by"], name="core_import_created_50035d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customfielddefinition",
            unique_together={("model_name", "field_name")},
        ),
        migrations.AddField(
            model_name="importtask",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Oluşturan",
            ),
        ),
        migrations.AddField(
            model_name="importsummary",
            name="import_task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="summary",
                to="core.importtask",
                verbose_name="İçe Aktarma Görevi",
            ),
        ),
        migrations.AddField(
            model_name="detailedimportresult",
            name="import_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detailed_results",
                to="core.importtask",
                verbose_name="İçe Aktarma Görevi",
            ),
        ),
        migrations.AddField(
            model_name="ruleset",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_rule_sets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Oluşturan",
            ),
        ),
        migrations.AddField(
            model_name="validationlog",
            name="rule_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="validation_logs",
                to="core.ruleset",
                verbose_name="Kural Seti",
            ),
        ),
        migrations.AddField(
            model_name="ruleset",
            name="rules",
            field=models.ManyToManyField(
                to="core.validationrule", verbose_name="Kurallar"
            ),
        ),
        migrations.DeleteModel(
            name="ImportError",
        ),
        migrations.DeleteModel(
            name="ImportJob",
        ),
        migrations.DeleteModel(
            name="ImportTemplate",
        ),
        migrations.AlterUniqueTogether(
            name="ruleset",
            unique_together={("model_name", "field_name")},
        ),
    ]
