# Generated by Django 5.2.1 on 2025-05-14 13:50

import django.db.models.deletion
import django.utils.timezone
import invoices.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Fatura Numarası')),
                ('invoice_type', models.CharField(choices=[('standard', 'Standart'), ('proforma', 'Proforma'), ('credit', 'İade')], default='standard', max_length=20, verbose_name='Fatura Tipi')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('issued', 'Kesildi'), ('paid', 'Ödendi'), ('cancelled', 'İptal Edildi'), ('refunded', 'İade Edildi')], default='draft', max_length=20, verbose_name='Durum')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fatura Tarihi')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Son Ödeme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ara Toplam')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='KDV Tutarı')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kargo Ücreti')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='İndirim Tutarı')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam Tutar')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=invoices.models.invoice_pdf_path, verbose_name='PDF Dosyası')),
                ('html_content', models.TextField(blank=True, verbose_name='HTML İçeriği')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Gönderildi')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='Gönderilme Tarihi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='orders.order', verbose_name='Sipariş')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturalar',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Açıklama')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miktar')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim Fiyat')),
                ('tax_rate', models.IntegerField(default=18, verbose_name='KDV Oranı (%)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='İndirim Tutarı')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice', verbose_name='Fatura')),
            ],
            options={
                'verbose_name': 'Fatura Kalemi',
                'verbose_name_plural': 'Fatura Kalemleri',
                'ordering': ['id'],
            },
        ),
    ]
