# Generated by Django 5.0.14 on 2025-05-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Anahtar')),
                ('value', models.TextField(verbose_name='Değer')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('category', models.CharField(choices=[('general', 'Genel'), ('email', 'E-posta'), ('advanced', 'Gelişmiş'), ('security', 'Güvenlik')], default='general', max_length=50, verbose_name='Kategori')),
                ('is_public', models.BooleanField(default=True, help_text='Public settings are visible to all authenticated users', verbose_name='Herkese Açık')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Sistem Ayarı',
                'verbose_name_plural': 'Sistem Ayarları',
                'ordering': ['category', 'key'],
            },
        ),
    ]
