# Generated by Django 5.0.14 on 2025-05-14 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Rapor Adı')),
                ('type', models.CharField(choices=[('sales', 'Satış Raporu'), ('customer', 'Müşteri Raporu'), ('product', 'Ürün Raporu'), ('inventory', 'Stok Raporu'), ('custom', 'Özel Rapor')], max_length=20, verbose_name='Rapor Tipi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('parameters', models.JSONField(default=dict, verbose_name='Rapor Parametreleri')),
                ('is_shared', models.BooleanField(default=False, verbose_name='Paylaşımlı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Kaydedilmiş Rapor',
                'verbose_name_plural': 'Kaydedilmiş Raporlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
