"""
Django settings for VivaCRM v2 project.

Generated by 'django-admin startproject' using Django 5.0.14.
"""

import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# Bu ayarlar development.py veya production.py'de override edilecek
SECRET_KEY = "development-only-key"  # Production'da environment'tan alınacak
DEBUG = True  # Production'da False olacak
ALLOWED_HOSTS = []  # Her ortamda farklı olacak

# Security settings
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
CSRF_COOKIE_SECURE = True if not DEBUG else False
SESSION_COOKIE_SECURE = True if not DEBUG else False
SECURE_SSL_REDIRECT = True if not DEBUG else False
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True if not DEBUG else False
SECURE_HSTS_PRELOAD = True if not DEBUG else False

# Application definition

# Import the base installed apps to avoid overwriting
from .base_apps import BASE_INSTALLED_APPS

INSTALLED_APPS = BASE_INSTALLED_APPS.copy()

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",  # Django Debug Toolbar
    # Custom middleware commented out for initial setup
    # "core.security.SecurityHeadersMiddleware",  # Custom security headers
    # "core.logging_filters.TraceIdMiddleware",  # Request tracing for logs
    # "core.middleware.SecurityAuditMiddleware",  # Security audit logging
    # "core.middleware.APIAccessLoggingMiddleware",  # API access logging
    # "core.middleware.PerformanceMonitoringMiddleware",  # Performance monitoring
    # "core.middleware.cache_middleware.CacheMonitoringMiddleware",  # Cache monitoring 
    # "core.middleware.cache_middleware.CachePurgeSignalMiddleware",  # Cache purging
]

# Only add SQL query counting middleware in DEBUG mode
if DEBUG:
    MIDDLEWARE.append("core.query_optimizer.QueryCountMiddleware")  # Advanced SQL query counting

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.sidebar_context",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Cache
# For development, use LocMem cache
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    },
    # Session cache
    "sessions": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "session-snowflake",
    },
    # Cache for storing longer-term data
    "long_term": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "longterm-snowflake",
        "TIMEOUT": 60 * 60 * 24 * 30,  # 30 days
    },
}

# For development without Redis, comment out the above and use this instead
# CACHES = {
#     "default": {
#         "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
#         "LOCATION": "unique-snowflake",
#     }
# }

# Celery Configuration
CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = "default"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Europe/Istanbul"
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
CELERY_TASK_ALWAYS_EAGER = True  # Run tasks immediately for development

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "tr"

TIME_ZONE = "Europe/Istanbul"

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ("tr", _("Turkish")),
    ("en", _("English")),
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Site ID (required for django.contrib.sites)
SITE_ID = 1

# Django Debug Toolbar
INTERNAL_IPS = [
    "127.0.0.1",
]

# Django REST Framework
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/day",
        "user": "1000/day",
    },
    "EXCEPTION_HANDLER": "core.api.exception_handlers.custom_exception_handler",
}

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    "TITLE": "VivaCRM API",
    "DESCRIPTION": "VivaCRM v2 API documentation",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"

# Custom User Model 
AUTH_USER_MODEL = "accounts.User"

# Login URL
LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "dashboard:dashboard"
LOGOUT_REDIRECT_URL = "accounts:login"

# Use cache for session storage (Redis kullanıyorsak)
# SESSION_ENGINE = "django.contrib.sessions.backends.cache"
# SESSION_CACHE_ALIAS = "session"
# Veya database kullanmaya devam edin:
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_AGE = 86400  # 1 day in seconds

# Email Backend (for development)
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "info@vivacrm.com"

# Redis ayarlarını import et
try:
    from .settings_redis import *
except ImportError:
    # Redis ayarları yüklenemediyse varsayılan cache kullan
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }

# Vite ayarlarını import et
try:
    from .vite import VITE_APP_DIR, VITE_DEV_MODE, VITE_DEV_SERVER_URL, VITE_MANIFEST_PATH, VITE_STATIC_URL, VITE_ASSETS_INCLUSION, VITE_APP_NAME
    
    # Ensure django_vite is in INSTALLED_APPS
    if VITE_APP_NAME not in INSTALLED_APPS:
        INSTALLED_APPS.append(VITE_APP_NAME)
except ImportError:
    pass
SERVER_EMAIL = "admin@vivacrm.com"

# Monitoring & Logging Configuration

# Sentry (Error Tracking)
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.redis import RedisIntegration
from sentry_sdk.integrations.celery import CeleryIntegration

SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            RedisIntegration(),
            CeleryIntegration(),
        ],
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for performance monitoring.
        # We recommend adjusting this value in production.
        traces_sample_rate=0.5,
        # Set profiles_sample_rate to 1.0 to profile 100%
        # of sampled transactions.
        # We recommend adjusting this value in production.
        profiles_sample_rate=0.3,
        # If you wish to associate users to errors (assuming you are using
        # django.contrib.auth):
        send_default_pii=True,
        environment=os.environ.get('ENVIRONMENT', 'development'),
    )

# Elastic APM (Application Performance Monitoring)
ELASTIC_APM = {
    'SERVICE_NAME': 'vivacrm',
    'SERVER_URL': os.environ.get('ELASTIC_APM_SERVER_URL', ''),
    'SECRET_TOKEN': os.environ.get('ELASTIC_APM_SECRET_TOKEN', ''),
    'ENVIRONMENT': os.environ.get('ENVIRONMENT', 'development'),
    'DEBUG': DEBUG,
}

if ELASTIC_APM['SERVER_URL']:
    INSTALLED_APPS += [
        'elasticapm.contrib.django',
    ]
    # Insert middleware at the beginning rather than replacing
    MIDDLEWARE.insert(0, 'elasticapm.contrib.django.middleware.TracingMiddleware')

# Django Prometheus (Metrics)
PROMETHEUS_APPS = [
    'django_prometheus',
    'health_check',
    'health_check.db',
    'health_check.cache',
    'health_check.storage',
    'health_check.contrib.celery',
]

# Simply add Prometheus apps to INSTALLED_APPS
for app in PROMETHEUS_APPS:
    if app not in INSTALLED_APPS:
        INSTALLED_APPS.append(app)

# Insert Prometheus middleware without overwriting entire MIDDLEWARE list
MIDDLEWARE.insert(0, 'django_prometheus.middleware.PrometheusBeforeMiddleware')
MIDDLEWARE.append('django_prometheus.middleware.PrometheusAfterMiddleware')

# Traditional Logging Configuration
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'json': {
            'format': '{"time": "%(asctime)s", "level": "%(levelname)s", "message": "%(message)s", "module": "%(module)s", "trace_id": "%(trace_id)s"}',
            'style': '%',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'add_trace_id': {
            '()': 'core.logging_filters.TraceIdFilter',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true', 'add_trace_id'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'vivacrm.log',
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'filters': ['add_trace_id'],
        },
        'security_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'security.log',
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'json',
            'filters': ['add_trace_id'],
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'error.log',
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'filters': ['add_trace_id'],
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'mail_admins'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.security': {
            'handlers': ['security_file', 'mail_admins'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'core.security': {
            'handlers': ['security_file', 'console', 'mail_admins'],
            'level': 'INFO',
            'propagate': False,
        },
        'core.middleware': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'vivacrm': {  # Project-specific logger
            'handlers': ['file', 'console', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'elasticapm.errors': {
            'level': 'ERROR',
            'handlers': ['console', 'error_file'],
            'propagate': False,
        },
        'django_prometheus': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Security settings - additional
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# Performance monitoring settings
SLOW_REQUEST_THRESHOLD = 1.0  # seconds

# Django Debug Toolbar Settings
def show_toolbar(request):
    """Show toolbar on all requests except AJAX"""
    return DEBUG and not request.headers.get('X-Requested-With') == 'XMLHttpRequest'

if DEBUG:
    # DEBUG_TOOLBAR_CONFIG = {
    #     "SHOW_TOOLBAR_CALLBACK": show_toolbar,
    #     "INTERCEPT_REDIRECTS": False,
    #     "DISABLE_PANELS": [
    #         "debug_toolbar.panels.redirects.RedirectsPanel",
    #     ],
    #     "SHOW_COLLAPSED": True,  # Toolbar'ı kapalı olarak başlat
    # }
    # Temporarily disable toolbar
    DEBUG_TOOLBAR_CONFIG = {
        "SHOW_TOOLBAR_CALLBACK": lambda request: False,
    }
