# Generated by Django 5.2.1 on 2025-05-14 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Adı')),
                ('type', models.CharField(choices=[('individual', 'Bireysel'), ('corporate', 'Kurumsal')], default='individual', max_length=20, verbose_name='Müşteri Tipi')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Şirket Adı')),
                ('tax_office', models.CharField(blank=True, max_length=255, verbose_name='Vergi Dairesi')),
                ('tax_number', models.CharField(blank=True, max_length=20, verbose_name='Vergi No / TC Kimlik No')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('website', models.URLField(blank=True, verbose_name='Web Sitesi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_customers', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu Kişi')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ad Soyad')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Unvan')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departman')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Birincil Kişi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'İlgili Kişi',
                'verbose_name_plural': 'İlgili Kişiler',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Adres Başlığı')),
                ('type', models.CharField(choices=[('billing', 'Fatura Adresi'), ('shipping', 'Teslimat Adresi'), ('other', 'Diğer')], default='other', max_length=20, verbose_name='Adres Tipi')),
                ('address_line1', models.CharField(max_length=255, verbose_name='Adres Satırı 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Adres Satırı 2')),
                ('city', models.CharField(max_length=100, verbose_name='Şehir')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='İlçe')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Posta Kodu')),
                ('country', models.CharField(default='Türkiye', max_length=100, verbose_name='Ülke')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Adres',
                'verbose_name_plural': 'Adresler',
                'ordering': ['-is_default', 'title'],
            },
        ),
    ]
