global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alert_rules.yml"

scrape_configs:
  # Django application metrics
  - job_name: 'django'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['web:8000']
    
  # Node exporter for host metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    
  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    
  # PostgreSQL (if you add postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']