# Generated by Django 5.2.1 on 2025-05-14 13:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Sipariş Numarası')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('pending', 'Beklemede'), ('processing', 'İşleniyor'), ('shipped', 'Kargoya Verildi'), ('delivered', 'Teslim Edildi'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi'), ('refunded', 'İade Edildi')], default='draft', max_length=20, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sipariş Tarihi')),
                ('shipping_date', models.DateTimeField(blank=True, null=True, verbose_name='Kargo Tarihi')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Teslim Tarihi')),
                ('payment_method', models.CharField(blank=True, choices=[('credit_card', 'Kredi Kartı'), ('bank_transfer', 'Banka Havalesi'), ('cash', 'Nakit'), ('online_payment', 'Online Ödeme'), ('other', 'Diğer')], max_length=20, verbose_name='Ödeme Yöntemi')),
                ('payment_status', models.CharField(choices=[('pending', 'Beklemede'), ('paid', 'Ödendi'), ('partially_paid', 'Kısmen Ödendi'), ('refunded', 'İade Edildi'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Ödeme Durumu')),
                ('payment_notes', models.TextField(blank=True, verbose_name='Ödeme Notları')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ara Toplam')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='KDV Tutarı')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kargo Ücreti')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='İndirim Tutarı')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam Tutar')),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_orders', to='customers.address', verbose_name='Fatura Adresi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer', verbose_name='Müşteri')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu Kişi')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_orders', to='customers.address', verbose_name='Teslimat Adresi')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miktar')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim Fiyat')),
                ('tax_rate', models.IntegerField(default=18, verbose_name='KDV Oranı (%)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='İndirim Tutarı')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Sipariş')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Sipariş Kalemi',
                'verbose_name_plural': 'Sipariş Kalemleri',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Kredi Kartı'), ('bank_transfer', 'Banka Havalesi'), ('cash', 'Nakit'), ('online_payment', 'Online Ödeme'), ('other', 'Diğer')], max_length=20, verbose_name='Ödeme Yöntemi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ödeme Tarihi')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='İşlem Numarası')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('is_successful', models.BooleanField(default=True, verbose_name='Başarılı')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Sipariş')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=100, verbose_name='Kargo Firması')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Takip Numarası')),
                ('shipping_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kargoya Verilme Tarihi')),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Tahmini Teslimat')),
                ('actual_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Gerçekleşen Teslimat')),
                ('status', models.CharField(choices=[('preparing', 'Hazırlanıyor'), ('shipped', 'Kargoya Verildi'), ('in_transit', 'Taşınıyor'), ('delivered', 'Teslim Edildi'), ('returned', 'İade Edildi'), ('failed', 'Başarısız')], default='preparing', max_length=20, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order', verbose_name='Sipariş')),
            ],
            options={
                'verbose_name': 'Kargo',
                'verbose_name_plural': 'Kargolar',
                'ordering': ['-shipping_date'],
            },
        ),
    ]
