# Generated by Django 5.2.1 on 2025-05-14 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase', 'Satın Alma'), ('sale', 'Satış'), ('return', 'İade'), ('adjustment', 'Stok Düzeltme'), ('inventory', 'Envanter Sayımı'), ('transfer', 'Transfer'), ('waste', 'Fire')], max_length=20, verbose_name='Hareket Tipi')),
                ('quantity', models.IntegerField(verbose_name='Miktar')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='Referans')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('previous_stock', models.PositiveIntegerField(default=0, verbose_name='Önceki Stok')),
                ('new_stock', models.PositiveIntegerField(default=0, verbose_name='Yeni Stok')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Birim Maliyet')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Stok Hareketi',
                'verbose_name_plural': 'Stok Hareketleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
