# Generated by Django 5.2.1 on 2025-05-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='threshold_stock',
            field=models.PositiveIntegerField(default=5, help_text='Stok bu seviyenin altına düştüğünde uyarı verilir', verbose_name='Kritik Stok Seviyesi'),
        ),
    ]
