# Generated by Django 5.0.1 on 2025-05-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productfamily_alter_stockmovement_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfamily',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Aile Adı'),
        ),
        migrations.AlterField(
            model_name='productfamily',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
