# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productfamily_name_alter_productfamily_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='asin',
            field=models.CharField(blank=True, help_text='Amazon Standard Identification Number', max_length=50, verbose_name='ASIN'),
        ),
    ]