# Generated by Django 5.0.14 on 2025-05-18 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_add_asin_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["name", "slug"], name="products_ca_name_603dc0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_active", "created_at"],
                name="products_ca_is_acti_b19b49_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["parent", "is_active"], name="products_ca_parent__1cafc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["code", "is_active"], name="products_pr_code_a51b6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["slug", "is_active"], name="products_pr_slug_280dfb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_active"], name="products_pr_categor_50f5f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["stock", "threshold_stock"], name="products_pr_stock_300efe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["price", "is_active"], name="products_pr_price_ce096c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["created_at", "is_active"],
                name="products_pr_created_a63638_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "is_active"], name="products_pr_status_c4a457_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["barcode"], name="products_pr_barcode_e44f4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="products_pr_sku_ca0cdc_idx"),
        ),
        migrations.AddIndex(
            model_name="productattribute",
            index=models.Index(
                fields=["name", "is_active"], name="products_pr_name_4fc7c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productattribute",
            index=models.Index(
                fields=["slug", "is_active"], name="products_pr_slug_de4fcb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productattributevalue",
            index=models.Index(
                fields=["product", "attribute"], name="products_pr_product_c00cf1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productattributevalue",
            index=models.Index(
                fields=["attribute", "value"], name="products_pr_attribu_99b421_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productfamily",
            index=models.Index(
                fields=["name", "is_active"], name="products_pr_name_c08b96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productfamily",
            index=models.Index(
                fields=["slug", "is_active"], name="products_pr_slug_03a6fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product", "is_primary"], name="products_pr_product_1b7905_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product", "order"], name="products_pr_product_e55bb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["product", "created_at"], name="products_st_product_a806c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["movement_type", "created_at"],
                name="products_st_movemen_62ae33_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["created_by", "created_at"],
                name="products_st_created_3e22d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["reference"], name="products_st_referen_6fb138_idx"
            ),
        ),
    ]
